# Generated by Django 3.1.2 on 2020-10-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_offer',
            field=models.CharField(blank=True, default='10% off', max_length=100, null=True),
        ),
    ]
