# Generated by Django 3.1.2 on 2020-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_sell_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_category',
            field=models.CharField(choices=[('Flider', 'Slider'), ('Featured', 'Featured'), ('Banner', 'Banner'), ('Product', 'Product')], default='Product', max_length=20),
        ),
    ]
