# Generated by Django 3.1.2 on 2020-10-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_category',
            field=models.CharField(choices=[('Slider', 'Slider'), ('Featured', 'Featured'), ('Banner', 'Banner'), ('Product', 'Product')], default='Product', max_length=20),
        ),
    ]
