# Generated by Django 3.1.2 on 2020-10-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201022_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category.png', upload_to='Category/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
